# lsd configuration
# https://github.com/lsd-rs/lsd

classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: auto
  theme: custom

icons:
  when: auto
  theme: fancy
  separator: " "

layout: grid
sorting:
  column: name
  reverse: false
  dir-grouping: first

date: date
size: default
permission: rwx
no-symlink: true

symlink-arrow: "â‡’"
